# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yemek', '0002_auto_20161013_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='Recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yemek.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='Recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yemek.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
