# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yemek', '0003_auto_20161013_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='Recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='recipestep',
            old_name='Recipe',
            new_name='recipe',
        ),
    ]
