# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yemek', '0004_auto_20161013_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='desc',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
